version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      sh -c "python backend/manage.py migrate --noinput &&
             python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - db-volume:/app/backend/db
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-volume:
  postgres_data:
