# Generated by Django 4.2.12 on 2025-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_public', 'created_at'], name='idx_public_comments'),
        ),
        migrations.AddIndex(
            model_name='servicecomment',
            index=models.Index(fields=['is_public', 'created_at'], name='idx_public_service_comments'),
        ),
    ]
