# Generated by Django 4.2.12 on 2025-11-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departure',
            new_name='Schedule',
        ),
        migrations.AlterModelOptions(
            name='reserveservice',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Reserve Service', 'verbose_name_plural': 'Reserve Services'},
        ),
        migrations.RenameField(
            model_name='reserveservice',
            old_name='approved',
            new_name='activation',
        ),
        migrations.RenameField(
            model_name='reserveservice',
            old_name='title',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='train',
            new_name='service',
        ),
        migrations.AddIndex(
            model_name='reserveservice',
            index=models.Index(fields=['-updated_at', '-created_at', 'activation'], name='idx_active_recent_reservations'),
        ),
        migrations.AddIndex(
            model_name='reserveservice',
            index=models.Index(fields=['user', 'activation', '-updated_at'], name='idx_user_active_reservations'),
        ),
        migrations.AddIndex(
            model_name='reserveservice',
            index=models.Index(fields=['date', 'activation'], name='idx_date_active_reservations'),
        ),
    ]
