# Generated by Django 4.2.12 on 2025-12-06 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_rename_departure_schedule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserveservice',
            unique_together={('user', 'date')},
        ),
    ]
