# Generated by Django 4.2.12 on 2025-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reserveservice_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reserveservice',
            index=models.Index(fields=['user', 'admin_approval'], name='idx_user_approved_turn'),
        ),
    ]
